name: 'Endjin.RecommendedPractices.Build.RunBuildScript'
description: 'Runs the standardised build script'
inputs:
  displayName:
    description: The display name given to the step running the build script
    required: true
    default: 'Run Build Script'
  netSdkVersion:
    description: The primary .NET SDK version required for the build process, as per the syntax required by the 'setup-dotnet' action.
    required: true
    default: '6.0.x'
  additionalNetSdkVersion:
    description: An additional .NET SDK version required for the build process, as per the syntax required by the 'setup-dotnet' action.
    required: false
  pythonVersion:
    description: Specify an additional Python version required for the build process
    required: false
  netSdkQuality:
    description: Allows pre-release versions of the .NET SDK to be installed, valid values are 'ga', 'preview', 'validated', 'signed' & 'daily' 
    required: false
    default: 'ga'
  tasks:
    description: The tasks that need to be run as part of the build script, formatted as a comma-delimited string (e.g. 'FullBuild' or 'Build,Test').
    required: true
  inputCacheKeySuffix:
    description: A string that will be appended to the generated cache key used this build script execution
    required: false
    default: 'build'
  outputCacheKeySuffix:
    description: A string that will be appended to the generated cache key used this build script execution
    required: false
    default: 'build'
  inputCachePaths:
    description: The caches paths that are consumed/required by this build script execution
    required: false
    default: ''
  outputCachePaths:
    description: The caches paths that are updated by this build script execution
    required: false
    default: ''
  configuration:
    description: The build configuration to use
    required: false
    default: 'Release'
  artifactName:
    description: If set, uploads a GitHub artifact with the provided name (path must be specified in `artifactPath`)
    required: false
    default: ''
  artifactPath:
    description: If set, uploads a GitHub artifact with the provided path (name must be specified in `artifactName`). The path can be a file, directory or wildcard pattern; multiple paths can be specified using newline demiliter.
    required: false
    default: ''
  buildScriptPath:
    description: The path to the build script to run.
    required: false
    default: './build.ps1'
  enableCrossOsCaching:
    description: "When true the enables the 'enableCrossOsArchive' property on the GitHub Actions cache task. ref: https://github.com/actions/cache/blob/main/tips-and-workarounds.md#cross-os-cache"
    required: false
    default: 'false'
  

outputs:
  semver:
    description: "The full SemVer version number of the current build"
    value: ${{ steps.run_script.outputs.SemVer }}
  major:
    description: "The major version component of the current build"
    value: ${{ steps.run_script.outputs.Major }}
  majorMinor:
    description: "The major & minor components of the current build"
    value: ${{ steps.run_script.outputs.Major }}.${{ steps.run_script.outputs.Minor }}
  preReleaseTag:
    description: "The pre-release tag, if any, of the current build"
    value: ${{ steps.run_script.outputs.PreReleaseTag }}

runs:
  using: "composite"
  steps:
  - uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309   # v5.1.0
    name: Install .NET Core SDK ${{ inputs.netSdkVersion }}
    with:
      dotnet-version: '${{ inputs.netSdkVersion }}'
      dotnet-quality: '${{ inputs.netSdkQuality }}'
  
  - uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309   # v5.1.0
    if: ${{ inputs.additionalNetSdkVersion }}
    name: Install .NET Core SDK ${{ inputs.additionalNetSdkVersion }}
    with:
      dotnet-version: '${{ inputs.additionalNetSdkVersion }}'
      dotnet-quality: '${{ inputs.netSdkQuality }}'

  - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405   # v6.2.0
    if: ${{ inputs.pythonVersion }}
    with:
      python-version: '${{ inputs.pythonVersion }}'

  - name: Debug cache paths (before)
    if: inputs.inputCachePaths != ''
    run: |
      echo "inputCachePaths: ${{ inputs.inputCachePaths }}"
      echo "outputCachePaths: ${{ inputs.outputCachePaths }}"
    shell: bash

  - name: Restore Cached Inputs
    if: inputs.inputCachePaths != ''
    id: cache_inputs_restore
    uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306    # v5.0.3
    with:
      path: ${{ inputs.inputCachePaths }}
      key: build-state-${{ github.run_id }}-${{ inputs.inputCacheKeySuffix }}
      enableCrossOsArchive: ${{ inputs.enableCrossOsCaching }}

  - name: Ensure required cached inputs are restored
    if: inputs.inputCachePaths != '' && steps.cache_inputs_restore.outputs.cache-hit == 'false'
    uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd   # v8.0.0
    with:
      script: |
        core.setFailed('Aborting build: GHA cache restore failure of required build state')
  
  - id: run_script
    name: ${{ inputs.displayName }}
    run: |
      $tasks = "${{ inputs.tasks }}" -split ","
      Write-Host "Running Tasks: $tasks"
      ${{ inputs.buildScriptPath }} -Tasks $tasks `
                  -Configuration ${{ inputs.configuration }}
    shell: pwsh
    env:
      GH_TOKEN: ${{ env.GH_TOKEN != '' && env.GH_TOKEN || github.token }}
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget-packages

  - name: Save Cached Outputs
    id: cache_outputs_save
    if: inputs.outputCachePaths
    uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306    # v5.0.3
    with:
      path: ${{ inputs.outputCachePaths }}
      key: build-state-${{ github.run_id }}-${{ inputs.outputCacheKeySuffix }}
      enableCrossOsArchive: ${{ inputs.enableCrossOsCaching }}

  - name: Upload Artifact
    uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02    # v4.6.2
    if: ${{ always() && inputs.artifactName != '' && inputs.artifactPath != '' }}
    with:
      name: ${{ inputs.artifactName }}
      path: ${{ inputs.artifactPath }}