name: 'Endjin.RecommendedPractices.Build.RunBuildScript'
description: 'Runs the standardised build script'
inputs:
  displayName:
    description: The display name given to the step running the build script
    required: true
    default: 'Run Build Script'
  netSdkVersion:
    description: The primary .NET SDK version required for the build process, as per the syntax required by the 'setup-dotnet' action.
    required: true
    default: '6.0.x'
  additionalNetSdkVersion:
    description: An additional .NET SDK version required for the build process, as per the syntax required by the 'setup-dotnet' action.
    required: false
  pythonVersion:
    description: Specify an additional Python version required for the build process
    required: false
  netSdkQuality:
    description: Allows pre-release versions of the .NET SDK to be installed, valid values are 'ga', 'preview', 'validated', 'signed' & 'daily' 
    required: false
    default: 'ga'
  tasks:
    description: The tasks that need to be run as part of the build script, formatted as a comma-delimited string (e.g. 'FullBuild' or 'Build,Test').
    required: true
  inputCachePaths:
    description: The caches paths that are consumed/required by this build script execution
    required: false
    default: ''
  outputCachePaths:
    description: The caches paths that are updated by this build script execution
    required: false
    default: ''
  configuration:
    description: The build configuration to use
    required: false
    default: 'Release'
  artifactName:
    description: If set, uploads a GitHub artifact with the provided name (path must be specified in `artifactPath`)
    required: false
    default: ''
  artifactPath:
    description: If set, uploads a GitHub artifact with the provided path (name must be specified in `artifactName`). The path can be a file, directory or wildcard pattern; multiple paths can be specified using newline demiliter.
    required: false
    default: ''
  buildScriptPath:
    description: The path to the build script to run.
    required: false
    default: './build.ps1'
  enableCrossOsCaching:
    description: "When true the enables the 'enableCrossOsArchive' property on the GitHub Actions cache task. ref: https://github.com/actions/cache/blob/main/tips-and-workarounds.md#cross-os-cache"
    required: false
    default: 'false'
  

outputs:
  semver:
    description: "The full SemVer version number of the current build"
    value: ${{ steps.run_script.outputs.SemVer }}
  major:
    description: "The major version component of the current build"
    value: ${{ steps.run_script.outputs.Major }}
  majorMinor:
    description: "The major & minor components of the current build"
    value: ${{ steps.run_script.outputs.Major }}.${{ steps.run_script.outputs.Minor }}
  preReleaseTag:
    description: "The pre-release tag, if any, of the current build"
    value: ${{ steps.run_script.outputs.PreReleaseTag }}

runs:
  using: "composite"
  steps:
  - uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25   # v4.1.0
    name: Install .NET Core SDK ${{ inputs.netSdkVersion }}
    with:
      dotnet-version: '${{ inputs.netSdkVersion }}'
      dotnet-quality: '${{ inputs.netSdkQuality }}'
  
  - uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25   # v4.1.0
    if: ${{ inputs.additionalNetSdkVersion }}
    name: Install .NET Core SDK ${{ inputs.additionalNetSdkVersion }}
    with:
      dotnet-version: '${{ inputs.additionalNetSdkVersion }}'
      dotnet-quality: '${{ inputs.netSdkQuality }}'

  - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3   # v5.2.0
    if: ${{ inputs.pythonVersion }}
    with:
      python-version: '${{ inputs.pythonVersion }}'

  - name: Debug cache paths (before)
    if: inputs.inputCachePaths != ''
    run: |
      echo "inputCachePaths: ${{ inputs.inputCachePaths }}"
      echo "outputCachePaths: ${{ inputs.outputCachePaths }}"
    shell: bash

  - name: Restore Cached Inputs
    if: inputs.inputCachePaths != ''
    id: cache_inputs_restore
    uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a    # v4.1.2
    with:
      path: ${{ inputs.inputCachePaths }}
      key: build-state-${{ github.sha }}
      enableCrossOsArchive: ${{ inputs.enableCrossOsCaching }}

  - id: cache_debug
    if: inputs.inputCachePaths != ''
    run: |
      echo "CacheHit: '${{ steps.cache_inputs_restore.outputs.cache-hit }}'"
    shell: bash
  
  - id: run_script
    name: ${{ inputs.displayName }}
    run: |
      $tasks = "${{ inputs.tasks }}" -split ","
      Write-Host "Running Tasks: $tasks"
      ${{ inputs.buildScriptPath }} -Tasks $tasks `
                  -Configuration ${{ inputs.configuration }}
    shell: pwsh
    env:
      GH_TOKEN: ${{ github.token }}
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget-packages

  - name: Save Cached Outputs
    id: cache_outputs_save
    if: inputs.outputCachePaths
    uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a    # v4.1.2
    with:
      path: ${{ inputs.outputCachePaths }}
      key: build-state-${{ github.sha }}
      enableCrossOsArchive: ${{ inputs.enableCrossOsCaching }}

  - name: Upload Artifact
    uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882    # v4.4.3
    if: ${{ always() && inputs.artifactName != '' && inputs.artifactPath != '' }}
    with:
      name: ${{ inputs.artifactName }}
      path: ${{ inputs.artifactPath }}