name: 'Endjin.RecommendedPractices.Build.RunBuildScript'
description: 'Runs the standardised build script'
inputs:
  displayName:
    description: The display name given to the step running the build script
    required: true
    default: 'Run Build Script'
  netSdkVersion:
    description: The primary .NET SDK version required for the build process, as per the syntax required by the 'setup-dotnet' action.
    required: true
    default: '6.0.x'
  additionalNetSdkVersion:
    description: An additional .NET SDK version required for the build process, as per the syntax required by the 'setup-dotnet' action.
    required: false
  netSdkQuality:
    description: Allows pre-release versions of the .NET SDK to be installed, valid values are 'ga', 'preview', 'validated', 'signed' & 'daily' 
    required: false
    default: 'ga'
  tasks:
    description: The tasks that need to be run as part of the build script, formatted as a comma-delimited string (e.g. 'FullBuild' or 'Build,Test').
    required: true
  inputCachePaths:
    description: The caches paths that are consumed/required by this build script execution
    required: false
    default: ''
  outputCachePaths:
    description: The caches paths that are updated by this build script execution
    required: false
    default: ''
  configuration:
    description: The build configuration to use
    required: false
    default: 'Release'
  artifactName:
    description: If set, uploads a GitHub artifact with the provided name (path must be specified in `artifactPath`)
    required: false
    default: ''
  artifactPath:
    description: If set, uploads a GitHub artifact with the provided path (name must be specified in `artifactName`). The path can be a file, directory or wildcard pattern; multiple paths can be specified using newline demiliter.
    required: false
    default: ''
  

outputs:
  semver:
    description: "The full SemVer version number of the current build"
    value: ${{ steps.run_script.outputs.SemVer }}
  major:
    description: "The major version component of the current build"
    value: ${{ steps.run_script.outputs.Major }}
  majorMinor:
    description: "The major & minor components of the current build"
    value: ${{ steps.run_script.outputs.Major }}.${{ steps.run_script.outputs.Minor }}
  preReleaseTag:
    description: "The pre-release tag, if any, of the current build"
    value: ${{ steps.run_script.outputs.PreReleaseTag }}

runs:
  using: "composite"
  steps:
  - uses: actions/setup-dotnet@v3
    name: Install .NET Core SDK ${{ inputs.netSdkVersion }}
    with:
      dotnet-version: '${{ inputs.netSdkVersion }}'
      dotnet-quality: '${{ inputs.netSdkQuality }}'
  
  - uses: actions/setup-dotnet@v3
    if: ${{ inputs.additionalNetSdkVersion }}
    name: Install .NET Core SDK ${{ inputs.additionalNetSdkVersion }}
    with:
      dotnet-version: '${{ inputs.additionalNetSdkVersion }}'
      dotnet-quality: '${{ inputs.netSdkQuality }}'

  - name: Debug cache paths (before)
    run: |
      echo "inputCachePaths: ${{ inputs.inputCachePaths }}"
      echo "outputCachePaths: ${{ inputs.outputCachePaths }}"
    shell: bash

  - name: Restore Cached Inputs
    if: inputs.inputCachePaths != ''
    id: cache_inputs_restore
    uses: actions/cache/restore@v3
    with:
      path: ${{ inputs.inputCachePaths }}
      key: build-state-${{ github.sha }}

  - id: cache_debug
    run: |
      echo "CacheHit: '${{ steps.cache_inputs_restore.outputs.cache-hit }}'"
    shell: bash
  
  - id: run_script
    name: ${{ inputs.displayName }}
    run: |
      $tasks = "${{ inputs.tasks }}" -split ","
      ./build.ps1 -Tasks $tasks `
                  -Configuration ${{ inputs.configuration }}
    shell: pwsh
    env:
      GH_TOKEN: ${{ github.token }}
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget-packages

  - name: Save Cached Outputs
    id: cache_outputs_save
    if: inputs.outputCachePaths
    uses: actions/cache/save@v3
    with:
      path: ${{ inputs.outputCachePaths }}
      key: build-state-${{ github.sha }}

  - name: Upload Artifact
    uses: actions/upload-artifact@v3
    if: ${{ always() && inputs.artifactName != '' && inputs.artifactPath != '' }}
    with:
      name: ${{ inputs.artifactName }}
      path: ${{ inputs.artifactPath }}